#!/usr/bin/env python3
"""
Compare LoRA Experiment 004 and GPT-4o-mini on external validation set.

Reference annotations come from metadata (GPT-4o judge), not from teacher
JSON in messages[2]. This script reads data/external_validation_reference.jsonl
or data/external_validation.jsonl and evaluates both models against the
external reference.

Usage on RunPod with live LoRA API:
    cd /workspace/hra-finetuning
    set -a; source .env; set +a
    .venv/bin/python scripts/compare_external_validation.py \
        --lora-api-url http://127.0.0.1:8000/v1/chat/completions \
        --input data/external_validation.jsonl \
        --output runs/experiment_004/external_validation_report.json
"""

import argparse
import json
import os
import time
import urllib.request
from pathlib import Path
from collections import Counter
from typing import Optional


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare LoRA vs GPT-4o-mini on external validation set"
    )
    parser.add_argument(
        "--input",
        type=str,
        default="data/external_validation.jsonl",
        help="External validation JSONL with reference annotations",
    )
    parser.add_argument(
        "--lora-api-url",
        type=str,
        default="http://127.0.0.1:8000/v1/chat/completions",
        help="LoRA API URL",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="runs/experiment_004/external_validation_report.json",
        help="Output report path",
    )
    parser.add_argument(
        "--max-tokens",
        type=int,
        default=512,
        help="Max tokens per response (default: 512)",
    )
    parser.add_argument(
        "--gpt-model",
        type=str,
        default="gpt-4o-mini",
        help="OpenAI model for comparison (default: gpt-4o-mini)",
    )
    return parser.parse_args()


def load_jsonl(path: str) -> list:
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def apply_response_format(messages: list) -> list:
    """Append JSON schema instruction to system message (matches benchmark_lora_engines.py)."""
    schema = {
        "type": "object",
        "properties": {
            "role_score": {"type": "number"},
            "skills_score": {"type": "number"},
            "experience_score": {"type": "number"},
            "conditions_score": {"type": "number"},
            "score": {"type": "number"},
            "decision": {"type": "string", "enum": ["match", "no_match"]},
            "reason": {"type": "string"},
        },
        "required": ["role_score", "skills_score", "experience_score", "conditions_score", "score", "decision", "reason"],
        "additionalProperties": False,
    }
    schema_instruction = (
        "\n\nВАЖНО. Ты работаешь как JSON API.\n"
        "Верни ТОЛЬКО валидный JSON-объект.\n"
        "Без markdown.\n"
        "Без пояснений.\n"
        "Без текста до JSON.\n"
        "Без текста после JSON.\n"
        "Без списков вне JSON.\n"
        "JSON должен соответствовать этой схеме:\n"
        + json.dumps(schema, ensure_ascii=False)
    )
    patched = [dict(m) for m in messages]
    if patched and patched[0].get("role") == "system":
        patched[0]["content"] = patched[0]["content"] + schema_instruction
    else:
        patched.insert(0, {"role": "system", "content": schema_instruction})
    return patched


def extract_json(text: str) -> Optional[dict]:
    text = text.strip()
    if text.startswith("```json"):
        text = text[7:]
    if text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    text = text.strip()
    try:
        return json.loads(text)
    except Exception:
        decoder = json.JSONDecoder()
        for i, ch in enumerate(text):
            if ch == "{":
                try:
                    obj, _ = decoder.raw_decode(text[i:])
                    return obj
                except json.JSONDecodeError:
                    continue
        return None


def call_lora_api(api_url: str, messages: list, max_tokens: int) -> tuple:
    """Call LoRA API without response_format/json_schema.

    vLLM's json_schema mode may transform or truncate the system prompt before
    it reaches the LoRA adapter, which was fine-tuned on the exact wording of
    the original system message. We therefore send the full prompt including the
    JSON instruction generated by apply_response_format() and rely on the
    adapter's training for JSON-only output, just like benchmark_lora_engines.py.
    """
    payload = {
        "model": "hra_exp004",
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": 0,
    }
    data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(
        api_url,
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    start = time.time()
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            body = resp.read().decode("utf-8")
            latency_ms = int((time.time() - start) * 1000)
            parsed = json.loads(body)
            content = parsed["choices"][0]["message"]["content"]
            result = extract_json(content)
            # If API returned graceful fallback envelope, treat as invalid JSON
            if result and result.get("error") == "invalid_json":
                return None, latency_ms, "LoRA API returned invalid_json fallback"
            return result, latency_ms, None
    except Exception as e:
        latency_ms = int((time.time() - start) * 1000)
        return None, latency_ms, str(e)


def call_gpt(model: str, messages: list, max_tokens: int) -> tuple:
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY environment variable is not set")

    schema = {
        "type": "object",
        "properties": {
            "role_score": {"type": "number"},
            "skills_score": {"type": "number"},
            "experience_score": {"type": "number"},
            "conditions_score": {"type": "number"},
            "score": {"type": "number"},
            "decision": {"type": "string", "enum": ["match", "no_match"]},
            "reason": {"type": "string"},
        },
        "required": ["role_score", "skills_score", "experience_score", "conditions_score", "score", "decision", "reason"],
        "additionalProperties": False,
    }
    payload = {
        "model": model,
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": 0,
        "response_format": {
            "type": "json_schema",
            "json_schema": {
                "name": "hra_matching",
                "strict": True,
                "schema": schema,
            },
        },
    }
    data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(
        "https://api.openai.com/v1/chat/completions",
        data=data,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        },
        method="POST",
    )
    start = time.time()
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            body = resp.read().decode("utf-8")
            latency_ms = int((time.time() - start) * 1000)
            parsed = json.loads(body)
            content = parsed["choices"][0]["message"]["content"]
            result = extract_json(content)
            return result, latency_ms, None
    except Exception as e:
        latency_ms = int((time.time() - start) * 1000)
        return None, latency_ms, str(e)


def score_one(pred, reference):
    if pred is None:
        return {"valid_json": False, "decision_match": False, "score_abs_error": None}
    def get(key):
        return pred.get(key) if isinstance(pred, dict) else None
    return {
        "valid_json": True,
        "decision_match": get("decision") == reference.get("decision"),
        "score_abs_error": abs(float(get("score") or 0) - float(reference.get("score") or 0)),
    }


def summarize(results, model_name):
    n = len(results)
    valid = sum(1 for r in results if r[f"{model_name}_metrics"]["valid_json"])
    decision_match = sum(1 for r in results if r[f"{model_name}_metrics"]["decision_match"])
    score_errors = [
        r[f"{model_name}_metrics"]["score_abs_error"]
        for r in results
        if r[f"{model_name}_metrics"]["score_abs_error"] is not None
    ]
    latencies = [r[f"{model_name}_latency_ms"] for r in results if r[f"{model_name}_latency_ms"] is not None]

    reference_decisions = Counter(r["reference"].get("decision") for r in results)
    model_decisions = Counter(
        r[f"{model_name}_prediction"].get("decision")
        if r[f"{model_name}_prediction"]
        else None
        for r in results
    )

    fp = sum(
        1
        for r in results
        if r["reference"].get("decision") == "no_match"
        and r[f"{model_name}_prediction"] is not None
        and r[f"{model_name}_prediction"].get("decision") == "match"
    )
    fn = sum(
        1
        for r in results
        if r["reference"].get("decision") == "match"
        and r[f"{model_name}_prediction"] is not None
        and r[f"{model_name}_prediction"].get("decision") == "no_match"
    )
    total_neg = reference_decisions.get("no_match", 0)
    total_pos = reference_decisions.get("match", 0)

    return {
        "model": model_name,
        "records": n,
        "valid_json_rate": valid / n if n else 0,
        "decision_accuracy": decision_match / n if n else 0,
        "mae_score": sum(score_errors) / len(score_errors) if score_errors else None,
        "fpr": fp / total_neg if total_neg else 0,
        "fnr": fn / total_pos if total_pos else 0,
        "latency_p50": sorted(latencies)[len(latencies) // 2] if latencies else None,
        "latency_p95": sorted(latencies)[int(len(latencies) * 0.95)] if latencies else None,
        "latency_avg": sum(latencies) / len(latencies) if latencies else None,
    }


def main():
    args = parse_args()

    rows = load_jsonl(args.input)

    results = []
    for i, row in enumerate(rows, 1):
        messages = row["messages"]
        meta = row.get("metadata", {})

        reference = {
            "role_score": meta.get("reference_role_score"),
            "skills_score": meta.get("reference_skills_score"),
            "experience_score": meta.get("reference_experience_score"),
            "conditions_score": meta.get("reference_conditions_score"),
            "score": meta.get("reference_score"),
            "decision": meta.get("reference_decision"),
            "reason": meta.get("reference_reason"),
        }

        print(f"[{i}/{len(rows)}] Evaluating {meta.get('case_code')} / {meta.get('vacancy_title')} ...")

        lora_pred, lora_lat, lora_err = call_lora_api(
            args.lora_api_url, apply_response_format(messages), args.max_tokens
        )
        gpt_pred, gpt_lat, gpt_err = call_gpt(args.gpt_model, messages, args.max_tokens)

        results.append({
            "metadata": meta,
            "reference": reference,
            "lora_prediction": lora_pred,
            "lora_latency_ms": lora_lat,
            "lora_error": lora_err,
            "lora_metrics": score_one(lora_pred, reference),
            "gpt_prediction": gpt_pred,
            "gpt_latency_ms": gpt_lat,
            "gpt_error": gpt_err,
            "gpt_metrics": score_one(gpt_pred, reference),
        })

    lora_summary = summarize(results, "lora")
    gpt_summary = summarize(results, "gpt")

    report = {
        "experiment": "experiment_004",
        "external_validation": {
            "dataset": "HRA-EVAL-V5-EXT",
            "experiment_code": "HRA-EXP-V5-EXT",
            "reference_judge": "gpt-4o",
            "total_records": len(rows),
        },
        "lora_api_url": args.lora_api_url,
        "gpt_model": args.gpt_model,
        "lora_summary": lora_summary,
        "gpt_summary": gpt_summary,
        "winner": (
            "lora"
            if lora_summary["decision_accuracy"] >= gpt_summary["decision_accuracy"]
            and (lora_summary["mae_score"] or 999) <= (gpt_summary["mae_score"] or 999)
            else "gpt"
        ),
        "results": results,
    }

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

    print("\nSUMMARY")
    print(json.dumps({
        "lora": lora_summary,
        "gpt": gpt_summary,
        "winner": report["winner"],
    }, ensure_ascii=False, indent=2))
    print(f"Report saved: {out_path}")


if __name__ == "__main__":
    main()
